spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://containers-us-west-139.railway.app:6594/railway
    username: postgres
    password: HcPILu6rrprTnotoRg8i

server:
  port: 8080